apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      name: client-pod
      labels:
        component: web
    spec:
      containers:
        - name: client-contianer
          image: rahulvdalal/multi-docker-client
          ports:
            - containerPort: 3000
